#
# This file is autogenerated during plugin quickstart and overwritten during
# plugin makedist. DO NOT CHANGE IT if you plan to use plugin makedist to update 
# the distribution.
#

from setuptools import setup, find_packages

kwargs = {'author': 'Mechanical Solutions Inc.',
 'author_email': '',
 'classifiers': ['Intended Audience :: Science/Research',
                 'Topic :: Scientific/Engineering'],
 'description': '',
 'download_url': 'github.com',
 'entry_points': '[openmdao.component]\nansyswrapper.ansyswrapper.ANSYSWrapperBase=ansyswrapper.ansyswrapper:ANSYSWrapperBase\n\n[openmdao.container]\nansyswrapper.ansyswrapper.ANSYSWrapperBase=ansyswrapper.ansyswrapper:ANSYSWrapperBase',
 'include_package_data': True,
 'install_requires': ['openmdao.main'],
 'keywords': ['openmdao'],
 'license': '',
 'maintainer': 'Mechanical Solutions Inc.',
 'maintainer_email': '',
 'name': 'ansyswrapper',
 'package_data': {'ansyswrapper': ['test\\test_ansyswrapper.py']},
 'package_dir': {'': 'src'},
 'packages': ['ansyswrapper'],
 'url': 'mechsol.com',
 'version': '0.1.0',
 'zip_safe': False}


setup(**kwargs)

